import RootProvider from "@/app/providers/root";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Header from "@/app/components/Header";
import { ButtonSwitchTheme } from "@/app/components/ButtonSwitchTheme";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.variable}`}>
        <RootProvider>
          <Header>
            <div>Logo</div>
            <div>
              <ButtonSwitchTheme text="Trocar tema" />
            </div>
          </Header>
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
